[package]
name = "leptos-transition-flip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos = "0.4.10"
web-sys = { version = "0.3.64", features = ["Element"] }
